modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = ""

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false
displayURL = "h"

[[mixins]]
config = "lostlegends-neoforge.mixins.json"

[[mixins]]
config = "lostlegends-common.mixins.json"

[[dependencies.${ modId }]]
modId = "minecraft"
required = true
versionRange = "[${minMinecraftVersion},)"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"