package sabledream.studios.lostlegends.client.render.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class MeerkatAnimation {

	public static final Animation DIGGING = Animation.Builder.create(1.75f)
		.addBoneAnimation("root",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, -23f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("root",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(57.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("head",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(47.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("leftArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(-30f, 0f, -17.5f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(-30f, 0f, -17.5f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(-32.5f, 0f, 20f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(-32.5f, 0f, 20f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("leftLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC))).build();
	public static final Animation BABY = Animation.Builder.create(0f)
		.addBoneAnimation("root",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.35f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("head",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -2f, 1f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("head",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.8f, 0.8f, 0.8f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("body",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.6f, 0.6f, 0.6f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leftArm",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.5f, -2f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leftArm",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.6f, 0.6f, 0.6f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("rightArm",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0.5f, -2f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("rightArm",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.6f, 0.6f, 0.6f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leftLeg",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -2f, -3f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leftLeg",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.6f, 0.6f, 0.6f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("rightLeg",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.25f, -2f, -2.5f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("rightLeg",
			new Transformation(Transformation.Targets.SCALE,
				new Keyframe(0f, AnimationHelper.createScalingVector(0.6f, 0.6f, 0.6f),
					Transformation.Interpolations.LINEAR))).build();
	public static final Animation DIGUP = Animation.Builder.create(2.25f)
		.addBoneAnimation("root",
			new Transformation(Transformation.Targets.TRANSLATE,
				new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -21f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("root",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-52.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leftArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(-30f, 0f, -17.5f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(-30f, 0f, -17.5f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(-30f, 0f, -17.5f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(-32.5f, 0f, 20f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(-32.5f, 0f, 20f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(-32.5f, 0f, 20f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("leftLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.75f, AnimationHelper.createRotationalVector(35.5f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC))).build();


	public static final Animation STAND_UP = Animation.Builder.create(0.24f).addBoneAnimation("head", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 9f, 8f), Transformation.Interpolations.LINEAR))).addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 13f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(-90f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("leftArm", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(1f, 7f, 6f), Transformation.Interpolations.LINEAR))).addBoneAnimation("leftArm", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(-25f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("rightArm", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(-1f, 7f, 6f), Transformation.Interpolations.LINEAR))).addBoneAnimation("rightArm", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(-25f, 0f, 0f), Transformation.Interpolations.LINEAR))).build();
	public static final Animation STOP_STAND = Animation.Builder.create(0.24f).addBoneAnimation("head", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 9f, 8f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 13f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(-90f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("leftArm", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 7f, 6f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("leftArm", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("rightArm", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(-1f, 7f, 6f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("rightArm", new Transformation(Transformation.Targets.ROTATE, new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.24f, AnimationHelper.createRotationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).build();





	public static final Animation WALK = Animation.Builder.create(1.5f).looping()
		.addBoneAnimation("leftArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightArm",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("leftLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC)))
		.addBoneAnimation("rightLeg",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.25f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.5f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.25f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
					Transformation.Interpolations.CUBIC),
				new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.CUBIC))).build();
}